backend = "full"
color_space = "lab"
threshold = 21
palette = "dark16"
generation = "complementary"
check_contrast = true

[templates]
cava.template = "templates/colors-cava"
cava.target = "~/.config/cava/config"

hypr.template = "templates/colors-hypr.conf"
hypr.target = "~/.config/hypr/themes/wallust.conf"

kitty.template = "templates/colors-kitty.conf"
kitty.target = "~/.config/kitty/kitty.conf"

macchina.template = "templates/colors-macchina.toml"
macchina.target = "~/.config/macchina/themes/wallust.toml"

rofi.template = "templates/colors-rofi.rasi"
rofi.target = "~/.config/rofi/shared/colors.rasi"

swaync.template = "templates/colors-swaync.css"
swaync.target = "~/.config/swaync/themes/wallust/colors-wallust.css"

waybar.template = "templates/colors-waybar.css"
waybar.target = "~/.config/waybar/wallust.css"

zathura.template = "templates/colors-zathura"
zathura.target = "~/.config/zathura/zathurarc"
